apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gateway-app
  template:
    metadata:
      labels:
        app: gateway-app
    spec:
      containers:
        - name: gateway
          image: 282865065290.dkr.ecr.us-east-1.amazonaws.com/gateway
          imagePullPolicy: Always
          ports:
            - containerPort: 3020
          env:
            - name: APPLICATION_PORT
              value: "3020"
            - name: SERVICE_AUTH_LOGIN
              value: http://auth-svc/auth/login
            - name: SERVICE_AUTH_VALIDATE_TOKEN
              value: http://auth-svc/auth/validate-token
            - name: SERVICE_USER_LIST
              value: http://user-svc/user
            - name: SERVICE_APPOINTMENT
              value: http://appointment-svc/appointment
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3020
            initialDelaySeconds: 3
            periodSeconds: 3
