post http://localhost:3000/user
content-type: application/json

{
    "name": "Carla",
    "lastname": "Martinez",
    "email": "carla.martinez@correo.com",
    "password": "12345678",
    "roles": [4, 5]
}