apiVersion: v1
kind: Namespace
metadata:
  name: nsp-prd
  labels:
    env: prd
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-prd
  namespace: nsp-prd
spec:
  limits:
    - max:
        memory: 1Gi
        cpu: 1
      min:
        memory: 100Mi
        cpu: 100m
      type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: server-nginx
  namespace: nsp-prd
  labels:
    env: prd
spec:
  containers:
    - name: server-nginx
      image: nginx:alpine
      resources:
        limits:
          memory: 2Gi
          cpu: 1
