apiVersion: v1
kind: Secret
metadata:
  name: secret-parameters
type: Opaque
data:
  db_host: ZGV2Lmhvc3QubG9jYWw=
  db-username: ZGV2LnVzZXI=
  db-password: ZGV2LnBhc3M=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-data
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
      env: dev
  template:
    metadata:
      labels:
        app: frontend
        env: dev
    spec:
      containers:
        - name: web01
          image: nginx:alpine
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: secret-parameters
                  key: db_host
