apiVersion: v1
kind: Namespace
metadata:
  name: nsp-dev
  labels:
    env: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: nsp-uat
  labels:
    env: uat
---
apiVersion: v1
kind: Namespace
metadata:
  name: nsp-prd
  labels:
    env: prd
