apiVersion: v1
kind: Service
metadata:
  name: svc-frontend
spec:
  type: NodePort
  selector:
    app: frontend
    env: dev
  ports:
    - nodePort: 30100
      port: 9600
      targetPort: 80
      protocol: TCP
