POST http://localhost/api/appointment
content-type: application/json

{
    "name": "Sergio",
    "lastname": "Hidalgo",
    "email": "hidalgo.sergio@email.com",
    "date": "2023-09-04T15:00:00.000Z",
    "medicId": "10",
    "specialtyId": "1",
    "centerId": "4",
    "isoCountryCode": "MX"
}