apiVersion: v1
kind: Namespace
metadata:
  name: nsp-stg
  labels:
    env: stg
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: demo-quota
  namespace: nsp-stg
spec:
  hard:
    pods: "3"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-data
  namespace: nsp-stg
spec:
  replicas: 2
  selector:
    matchLabels:
      env: stg
  template:
    metadata:
      labels:
        env: stg
    spec:
      containers:
        - name: web01
          image: nginx:alpine
