apiVersion: v1
kind: Namespace
metadata:
  name: nsp-qas
  labels:
    env: qas
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: demo-quota
  namespace: nsp-qas
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "1Gi"
    limits.cpu: "2"
    limits.memory: "2Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-data
  namespace: nsp-qas
spec:
  replicas: 5
  selector:
    matchLabels:
      env: qas
  template:
    metadata:
      labels:
        env: qas
    spec:
      containers:
        - name: web01
          image: nginx:alpine
          resources:
            limits:
              memory: 500Mi
              cpu: 500m
            requests:
              memory: 500Mi
              cpu: 500m
