apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-parameters
data:
  db_host: dev.host.local
  db-username: dev.user
  db-password: dev.pass
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-data
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
      env: dev
  template:
    metadata:
      labels:
        app: frontend
        env: dev
    spec:
      containers:
        - name: web01
          image: nginx:alpine
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: cm-parameters
                  key: db_host
