get http://localhost:3020/api/usuarios
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQ2FybGEgTWFjYXJlbmEiLCJsYXN0bmFtZSI6Ik1hcnRpbmV6IiwiZW1haWwiOiJjYXJsYS5tYXJ0aW5lekBjb3JyZW8uY29tIiwicm9sZXMiOls0LDVdLCJpYXQiOjE2OTMxMDA3NzAsImV4cCI6MTY5MzEwMDg5MH0.ZMUCampWyLJlUvX9boplxbYD0s3boeEk8ETSMFVRGNU
